<a href="https://colab.research.google.com/github/Mariamng/Learning/blob/main/IlmajaamPuhastatud_read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd


ilmajaam_df = pd.read_csv("/content/Tallinn-Harku-2004-juuni-2024CSV.csv", sep=';')
ilmajaam_df.head(n=10)

#puhastan ebavajalikud read

ilmajaam_df = ilmajaam_df.drop(columns=['Õhurõhk merepinna kõrgusel hPa', 'Õhurõhk jaama kõrgusel hPa', 'Suhteline õhuniiskus %','Tunni miinimum õhutemperatuur °C', 'Tunni maksimum õhutemperatuur °C', '10 minuti keskmine tuule kiirus m/s' ])
ilmajaam_df

,Aasta,Kuu,Päev,Kell (UTC),Tunni keskmine summaarne kiirgus W/m²,Tunni sademete summa mm,Õhutemperatuur °C,10 minuti keskmine tuule suund °,Tunni maksimum tuule kiirus m/s
0,2004,1,1,00:00,NaN,NaN,"-0,9",19.0,"7,7"
1,2004,1,1,01:00,NaN,NaN,"-1,5",17.0,"8,6"
2,2004,1,1,02:00,NaN,NaN,"-2,6",33.0,"9,9"
3,2004,1,1,03:00,NaN,NaN,"-2,5",22.0,"8,7"
4,2004,1,1,04:00,NaN,NaN,-3,26.0,"7,8"
...,...,...,...,...,...,...,...,...,...
179683,2024,6,30,19:00,17.0,0,"21,2",113.0,"4,9"
179684,2024,6,30,20:00,1.0,0,"20,4",99.0,"5,6"
179685,2024,6,30,21:00,0.0,0,19,122.0,7
179686,2024,6,30,22:00,0.0,0,19,129.0,"8,4"
179687,2024,6,30,23:00,0.0,"0,4","17,1",142.0,"7,9"

In [30]:
import pandas as pd

# Convert 'Kuu' and 'Päev' to INT before concatenation
ilmajaam_df['Kuu'] = ilmajaam_df['Kuu'].astype(int)
ilmajaam_df['Päev'] = ilmajaam_df['Päev'].astype(int)

# Combine 'Aasta', 'Kuu', and 'Päev' columns to create a 'Kuupäev' column in 'YYYY-MM-DD' format
ilmajaam_df['Kuupäev'] = pd.to_datetime(ilmajaam_df['Aasta'].astype(str) + '-' +
                                         ilmajaam_df['Kuu'].astype(str) + '-' +
                                         ilmajaam_df['Päev'].astype(str),
                                         format='%Y-%m-%d', errors='coerce')

# Ensure 'Õhutemperatuur °C' is numeric
ilmajaam_df['Õhutemperatuur °C'] = pd.to_numeric(ilmajaam_df['Õhutemperatuur °C'], errors='coerce')

# Convert 'Tunni sademete summa mm' to numeric before calculating the mean
ilmajaam_df['Tunni sademete summa mm'] = pd.to_numeric(ilmajaam_df['Tunni sademete summa mm'], errors='coerce')

# Clean the 'Tunni maksimum tuule kiirus m/s' column:
ilmajaam_df['Tunni maksimum tuule kiirus m/s'] = (
    ilmajaam_df['Tunni maksimum tuule kiirus m/s']
    .astype(str)
    .str.replace(',', '.')
    .str.replace('[^0-9.]', '', regex=True)
)
ilmajaam_df['Tunni maksimum tuule kiirus m/s'] = pd.to_numeric(ilmajaam_df['Tunni maksimum tuule kiirus m/s'], errors='coerce')

# Group by the 'Kuupäev' and calculate the average for each parameter
daily_average = pd.DataFrame()
daily_average['Kuupäev'] = ilmajaam_df.groupby('Kuupäev')['Kuupäev'].first()  # Get unique dates
daily_average['Keskmine_temperatuur'] = ilmajaam_df.groupby('Kuupäev')['Õhutemperatuur °C'].mean()
daily_average['Keskmine_kiirgus'] = ilmajaam_df.groupby('Kuupäev')['Tunni keskmine summaarne kiirgus W/m²'].mean()
daily_average['Keskmine_sade'] = ilmajaam_df.groupby('Kuupäev')['Tunni sademete summa mm'].mean()
daily_average['Keskmine_suund'] = ilmajaam_df.groupby('Kuupäev')['10 minuti keskmine tuule suund °'].mean()
daily_average['Keskmine_max_tuule_kiirus'] = ilmajaam_df.groupby('Kuupäev')['Tunni maksimum tuule kiirus m/s'].mean()

# Reset the index to ensure it's a clean DataFrame
daily_average.reset_index(drop=True, inplace=True)

# Display the daily averages
print(daily_average)

        Kuupäev  Keskmine_temperatuur  Keskmine_kiirgus  Keskmine_sade  \
0    2004-01-01             -3.666667               NaN            NaN
1    2004-01-02             -6.750000               NaN            NaN
2    2004-01-03            -10.000000               NaN            NaN
3    2004-01-04             -3.333333               NaN            NaN
4    2004-01-05             -1.000000               NaN            NaN
...         ...                   ...               ...            ...
7482 2024-06-26             20.000000        349.166667            0.0
7483 2024-06-27             23.500000        343.208333            0.0
7484 2024-06-28             29.500000        326.750000            0.0
7485 2024-06-29             18.000000        275.791667            0.0
7486 2024-06-30             18.800000        268.000000            0.0

      Keskmine_suund  Keskmine_max_tuule_kiirus
0          42.916667                  11.233333
1          61.958333                   9.320833
2         210.666667                   2.670833
3         233.375000                   4.212500
4         274.416667                   5.850000
...              ...                        ...
7482      254.250000                   5.266667
7483      221.291667                   3.512500
7484      161.916667                   5.920833
7485      238.458333                   7.637500
7486      160.625000                   5.562500

[7487 rows x 6 columns]